version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  telegram:
    build: ./telegram
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./telegram:/app    

  discord:
    build: ./discord
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./discord:/apps
 
  bot_logic:
    build: ./app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./app:/app